/*
 * Copyright (c) 2013 Pezzutti Marco
 * 
 * This file is part of Sistema Trasporti Artici (progetto per l'insegnamento 
 * di Programmazione Concorrente e Distribuita).

 * Sistema Trasporti Artici is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Sistema Trasporti Artici is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Sistema Trasporti Artici.  If not, see <http://www.gnu.org/licenses/>.
 */
package ditta;

import javax.swing.JOptionPane;
import javax.swing.text.DefaultCaret;

/**
 * Interfaccia grafica della Ditta di trasporti
 * 
 * @author Pezzutti Marco 1008804
 */
public class DittaGUI extends javax.swing.JFrame implements Runnable {
    Ditta ditta;
    
    private Thread creaOrdini;
    private boolean creaOrdiniAttivo;

    /**
     * Creates new form DittaGUI
     */
    DittaGUI() {
        initComponents();
        statoTextArea.setLineWrap(true);
        
        creaOrdiniAttivo = false;
        
        DefaultCaret  caret;
        
        //imposto l'autoscrolling di statoTextArea
        caret = (DefaultCaret) statoTextArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        
        //imposto l'autoscrolling di ordiniInseritiTextArea
        caret = (DefaultCaret) ordiniInseritiTextArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        
    }

    /**
     * Metodo che imposta la ditta propria della GUI
     * 
     * @param ditta                 riferimento alla Ditta
     */
    void setDitta(Ditta ditta) {
        this.ditta = ditta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inserimentoOrdiniPanel = new javax.swing.JPanel();
        basePartenzaLabel = new javax.swing.JLabel();
        baseDestinazioneLabel = new javax.swing.JLabel();
        basePartenzaComboBox = new javax.swing.JComboBox();
        baseDestinazioneComboBox = new javax.swing.JComboBox();
        quantitaOrdiniLabel = new javax.swing.JLabel();
        quantitaOrdiniSpinner = new javax.swing.JSpinner();
        inviaOrdineButton = new javax.swing.JButton();
        creaOrdiniButton = new javax.swing.JButton();
        statoPanel = new javax.swing.JPanel();
        statoScrollPane = new javax.swing.JScrollPane();
        statoTextArea = new javax.swing.JTextArea();
        terminaAttivitaButton = new javax.swing.JButton();
        ordiniInseritiPanel = new javax.swing.JPanel();
        ordiniInseritiScrollPane = new javax.swing.JScrollPane();
        ordiniInseritiTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Trasporti Artici");
        setResizable(false);

        inserimentoOrdiniPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Inserimento Ordini"));

        basePartenzaLabel.setText("Base Partenza");

        baseDestinazioneLabel.setText("Base Destinazione");

        quantitaOrdiniLabel.setText("Quantità di ordini");

        quantitaOrdiniSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        inviaOrdineButton.setText("Invia Ordine");
        inviaOrdineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviaOrdineButtonActionPerformed(evt);
            }
        });

        creaOrdiniButton.setText("Auto");
        creaOrdiniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaOrdiniButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inserimentoOrdiniPanelLayout = new javax.swing.GroupLayout(inserimentoOrdiniPanel);
        inserimentoOrdiniPanel.setLayout(inserimentoOrdiniPanelLayout);
        inserimentoOrdiniPanelLayout.setHorizontalGroup(
            inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inserimentoOrdiniPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inserimentoOrdiniPanelLayout.createSequentialGroup()
                        .addComponent(creaOrdiniButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inviaOrdineButton))
                    .addGroup(inserimentoOrdiniPanelLayout.createSequentialGroup()
                        .addGroup(inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(baseDestinazioneLabel)
                            .addComponent(basePartenzaLabel)
                            .addComponent(quantitaOrdiniLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantitaOrdiniSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(basePartenzaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(baseDestinazioneComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        inserimentoOrdiniPanelLayout.setVerticalGroup(
            inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inserimentoOrdiniPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basePartenzaLabel)
                    .addComponent(basePartenzaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baseDestinazioneLabel)
                    .addComponent(baseDestinazioneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantitaOrdiniLabel)
                    .addComponent(quantitaOrdiniSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inviaOrdineButton)
                    .addComponent(creaOrdiniButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        statoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Stato"));

        statoTextArea.setColumns(20);
        statoTextArea.setRows(5);
        statoTextArea.setEnabled(false);
        statoScrollPane.setViewportView(statoTextArea);

        javax.swing.GroupLayout statoPanelLayout = new javax.swing.GroupLayout(statoPanel);
        statoPanel.setLayout(statoPanelLayout);
        statoPanelLayout.setHorizontalGroup(
            statoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        statoPanelLayout.setVerticalGroup(
            statoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
        );

        terminaAttivitaButton.setText("Termina Attività");
        terminaAttivitaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminaAttivitaButtonActionPerformed(evt);
            }
        });

        ordiniInseritiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordini Inseriti"));

        ordiniInseritiTextArea.setColumns(20);
        ordiniInseritiTextArea.setRows(5);
        ordiniInseritiTextArea.setEnabled(false);
        ordiniInseritiScrollPane.setViewportView(ordiniInseritiTextArea);

        javax.swing.GroupLayout ordiniInseritiPanelLayout = new javax.swing.GroupLayout(ordiniInseritiPanel);
        ordiniInseritiPanel.setLayout(ordiniInseritiPanelLayout);
        ordiniInseritiPanelLayout.setHorizontalGroup(
            ordiniInseritiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ordiniInseritiScrollPane)
        );
        ordiniInseritiPanelLayout.setVerticalGroup(
            ordiniInseritiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ordiniInseritiScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ordiniInseritiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inserimentoOrdiniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(terminaAttivitaButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inserimentoOrdiniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ordiniInseritiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(terminaAttivitaButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo invocato alla pressione del pulsante Invia Ordine che recupera i nomi 
     * delle base di partenza e di arrivo e la quantità impostati e avvisa la Ditta
     * della presenza di un nuovo ordine
     * 
     * @param evt                   riferimento all'evento scatenato dal pulsante
     */
    private void inviaOrdineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviaOrdineButtonActionPerformed
        String partenza = (String) basePartenzaComboBox.getSelectedItem();
        String destinazione = (String) baseDestinazioneComboBox.getSelectedItem();
        int quantita = (Integer) quantitaOrdiniSpinner.getValue();
        
        if(!partenza.equals(destinazione)) {
            ditta.inserisciOrdine(partenza, destinazione, quantita);
        }
        else {
            JOptionPane.showMessageDialog(this, "La base di partenza e la base di "
                    + "destinazione devono essere diverse", "Attenzione", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_inviaOrdineButtonActionPerformed

    /**
     * Metodo invocato alla pressione del pulsante Termina Attività che avvisa 
     * la Ditta di terminare tutte le attività di trasporto
     * 
     * @param evt                   riferimento all'evento scatenato dal pulsante
     */
    private void terminaAttivitaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminaAttivitaButtonActionPerformed
        ditta.terminaAttivita();
    }//GEN-LAST:event_terminaAttivitaButtonActionPerformed

    /**
     * Metodo invocato alla pressione del pulsante Auto che si occupa di avviare 
     * un thread che crea ordini automaticamente alla prima pressione del pulsante, 
     * alla seconda pressione arresta la creazione automatica
     * @param evt 
     */
    private void creaOrdiniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaOrdiniButtonActionPerformed
        if(!creaOrdiniAttivo) {
            creaOrdini = ditta.avviaCreaOrdini();
            creaOrdini.start();
            creaOrdiniButton.setText("Stop");
            creaOrdiniAttivo = true;
        }
        else {
            creaOrdini.interrupt();
            creaOrdiniButton.setText("Auto");
            creaOrdiniAttivo = false;
        }
    }//GEN-LAST:event_creaOrdiniButtonActionPerformed

    /**
     * Metodo che rende visibile la GUI
     */
    @Override
    public void run() {
        this.setVisible(true);
    }
    
    /*
     * Metodo che aggiunge una base appena creata all'elenco delle basi
     */
    void aggiungiBaseComboBox(String base) {
        baseDestinazioneComboBox.addItem(base);
        basePartenzaComboBox.addItem(base);
    }
    
    /**
     * Metodo che rimuove la base passata come parametro dall'elenco delle basi
     * 
     * @param base                  nome della base da rimuovere
     */
    void rimuoviBaseComboBox(String base) {
        baseDestinazioneComboBox.removeItem(base);
        basePartenzaComboBox.removeItem(base);
    }
    
    /**
     * Metodo che aggiorna lo stato della Ditta
     * 
     * @param text                  stringa contenente un nuovo messaggio di stato
     */
    void aggiornaStatoTextArea(String text) {
        statoTextArea.append(text + "\n");
    }
    
    /**
     * Metodo che aggiorna la lista degli ordini
     * 
     * @param text                  stringa contenente l'elenco degli ordini
     */
    void aggiornaOrdiniTextArea(String text) {
        ordiniInseritiTextArea.setText(text + "\n");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox baseDestinazioneComboBox;
    private javax.swing.JLabel baseDestinazioneLabel;
    private javax.swing.JComboBox basePartenzaComboBox;
    private javax.swing.JLabel basePartenzaLabel;
    private javax.swing.JButton creaOrdiniButton;
    private javax.swing.JPanel inserimentoOrdiniPanel;
    private javax.swing.JButton inviaOrdineButton;
    private javax.swing.JPanel ordiniInseritiPanel;
    private javax.swing.JScrollPane ordiniInseritiScrollPane;
    private javax.swing.JTextArea ordiniInseritiTextArea;
    private javax.swing.JLabel quantitaOrdiniLabel;
    private javax.swing.JSpinner quantitaOrdiniSpinner;
    private javax.swing.JPanel statoPanel;
    private javax.swing.JScrollPane statoScrollPane;
    private javax.swing.JTextArea statoTextArea;
    private javax.swing.JButton terminaAttivitaButton;
    // End of variables declaration//GEN-END:variables
}