/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

/**
 *
 * @author marco
 */
public class BaseGUI extends javax.swing.JFrame implements Runnable {
    private Base base;

    /**
     * Creates new form baseGUI
     */
    public BaseGUI(String nomeBase) {
        initComponents();
        this.setTitle(nomeBase);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inserimentoOrdiniPanel = new javax.swing.JPanel();
        basePartenzaLabel = new javax.swing.JLabel();
        baseDestinazioneLabel = new javax.swing.JLabel();
        basePartenzaComboBox = new javax.swing.JComboBox();
        baseDestinazioneCOmboBox = new javax.swing.JComboBox();
        quantitaOrdiniLabel = new javax.swing.JLabel();
        quantitaOrdiniSpinner = new javax.swing.JSpinner();
        inviaOrdineButton = new javax.swing.JButton();
        statoPanel = new javax.swing.JPanel();
        statoScrollPanel = new javax.swing.JScrollPane();
        statoTextArea = new javax.swing.JTextArea();
        terminaAttivitaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inserimentoOrdiniPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Inserimento Ordini"));

        basePartenzaLabel.setText("Base Partenza");

        baseDestinazioneLabel.setText("Base Destinazione");

        basePartenzaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        baseDestinazioneCOmboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        quantitaOrdiniLabel.setText("Quantità di ordini");

        inviaOrdineButton.setText("Invia Ordine");

        javax.swing.GroupLayout inserimentoOrdiniPanelLayout = new javax.swing.GroupLayout(inserimentoOrdiniPanel);
        inserimentoOrdiniPanel.setLayout(inserimentoOrdiniPanelLayout);
        inserimentoOrdiniPanelLayout.setHorizontalGroup(
            inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inserimentoOrdiniPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inserimentoOrdiniPanelLayout.createSequentialGroup()
                        .addGroup(inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(baseDestinazioneLabel)
                            .addComponent(basePartenzaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(basePartenzaComboBox, 0, 197, Short.MAX_VALUE)
                            .addComponent(baseDestinazioneCOmboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(inserimentoOrdiniPanelLayout.createSequentialGroup()
                        .addComponent(quantitaOrdiniLabel)
                        .addGap(21, 21, 21)
                        .addComponent(quantitaOrdiniSpinner))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inserimentoOrdiniPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(inviaOrdineButton)))
                .addContainerGap())
        );
        inserimentoOrdiniPanelLayout.setVerticalGroup(
            inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inserimentoOrdiniPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basePartenzaLabel)
                    .addComponent(basePartenzaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baseDestinazioneLabel)
                    .addComponent(baseDestinazioneCOmboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inserimentoOrdiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantitaOrdiniLabel)
                    .addComponent(quantitaOrdiniSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(inviaOrdineButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        statoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Stato"));

        statoTextArea.setColumns(20);
        statoTextArea.setRows(5);
        statoTextArea.setEnabled(false);
        statoScrollPanel.setViewportView(statoTextArea);

        javax.swing.GroupLayout statoPanelLayout = new javax.swing.GroupLayout(statoPanel);
        statoPanel.setLayout(statoPanelLayout);
        statoPanelLayout.setHorizontalGroup(
            statoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statoScrollPanel)
        );
        statoPanelLayout.setVerticalGroup(
            statoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statoScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
        );

        terminaAttivitaButton.setText("Termina Attività");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inserimentoOrdiniPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(terminaAttivitaButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inserimentoOrdiniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(terminaAttivitaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    @Override
    public void run() {
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox baseDestinazioneCOmboBox;
    private javax.swing.JLabel baseDestinazioneLabel;
    private javax.swing.JComboBox basePartenzaComboBox;
    private javax.swing.JLabel basePartenzaLabel;
    private javax.swing.JPanel inserimentoOrdiniPanel;
    private javax.swing.JButton inviaOrdineButton;
    private javax.swing.JLabel quantitaOrdiniLabel;
    private javax.swing.JSpinner quantitaOrdiniSpinner;
    private javax.swing.JPanel statoPanel;
    private javax.swing.JScrollPane statoScrollPanel;
    private javax.swing.JTextArea statoTextArea;
    private javax.swing.JButton terminaAttivitaButton;
    // End of variables declaration//GEN-END:variables
}
